name: Build and test project

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build and test project
        run: |
          npm install
          npm build
          npm test

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: my-nginx-image:latest

      - name: Start Docker container
        run: |
          docker run -d --name my-container my-nginx-image:latest

      - name: Stop and remove container
        run: |
          docker stop my-container
          docker rm my-container